# Generated by Django 6.0.7 on 2026-07-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DonateBloodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('address', models.TextField()),
                ('last_donation', models.DateField(blank=True, null=True)),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestBloodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
                ('units_needed', models.IntegerField()),
                ('urgency', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=100)),
                ('required_by', models.DateField()),
                ('contact_phone', models.CharField(max_length=15)),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
