# Generated by Django 6.0.7 on 2026-07-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminZone', '0002_donormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=5)),
                ('weight', models.IntegerField()),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('last_donation', models.DateField(blank=True, null=True)),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('disease', models.CharField(max_length=20)),
                ('disease_details', models.TextField(blank=True)),
                ('medicine', models.CharField(max_length=20)),
                ('previous_donation', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='mob',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='request_type',
        ),
        migrations.AlterField(
            model_name='donormodel',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donormodel',
            name='disease',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donormodel',
            name='medicine',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donormodel',
            name='previous_donation',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donormodel',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
