# Generated by Django 6.0.7 on 2026-07-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminZone', '0003_donorregistermodel_remove_contactmodel_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='blood_group',
            field=models.CharField(default='O+', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='mob',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='msg',
            field=models.TextField(default='No Message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='request_type',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
