# Generated by Django 6.0.7 on 2026-07-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminZone', '0004_contactmodel_blood_group_contactmodel_mob_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorModel',
        ),
    ]
