# Generated by Django 6.0.7 on 2026-07-17 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminZone', '0005_delete_donormodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginModel',
        ),
        migrations.RemoveField(
            model_name='donorregistermodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='donorregistermodel',
            name='username',
        ),
        migrations.AddField(
            model_name='donorregistermodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
