# Generated by Django 6.0.7 on 2026-07-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminZone', '0006_delete_loginmodel_remove_donorregistermodel_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
