# Generated by Django 6.0.7 on 2026-07-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminZone', '0007_loginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatebloodmodel',
            name='status',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
